Repository RAIRLab/Peirce-My-Heart, pull requests merged in 2023-12, with the labels that each got.

#275 Copy after global move quick bug squash
  src/DrawModes/CopySingleTool.ts
Labels: bug, required

#277 Typedoc entry points
  package.json
  typedoc.json
Labels: bug, documentation, required

#149 Playwright integration!
  .github/workflows/playwright.yml
  .github/workflows/runTests.yml
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  playwright.config.js
  src/DrawModes/DrawUtils.ts
  src/about.html
  src/aeg.html
  src/index.ts
  tests/AEGTree/AEGTree.test.ts
  tests/AEGTree/AtomNode.test.ts
  tests/AEGTree/CutNode.test.ts
  tests/AEGTree/Ellipse.test.ts
  tests/AEGTree/Point.test.ts
  tests/AEGTree/Rectangle.test.ts
  tests/UI/aboutAEG.spec.ts
  tests/UI/aegInformation.spec.ts
  tests/UI/atom.spec.ts
  tests/UI/expectedTrees/disjunction.json
  tests/UI/expectedTrees/emptyTree.json
  tests/UI/expectedTrees/loneAtom.json
  tests/UI/expectedTrees/loneCut.json
  vite.config.js
Labels: enhancement, required

#287 284 clear proofs
  src/AEG/ProofNode.ts
  src/DrawModes/DragTool.ts
  src/DrawModes/DrawUtils.ts
  src/ProofHistory.ts
  src/ProofTools/ClearProofTool.ts
  src/ProofTools/DeiterationTool.ts
  src/ProofTools/DoubleCutDeletionTool.ts
  src/ProofTools/DoubleCutInsertionTool.ts
  src/ProofTools/ErasureTool.ts
  src/ProofTools/InsertionTools.ts
  src/ProofTools/IterationTool.ts
  src/ProofTools/ProofMoveMultiTool.ts
  src/ProofTools/ProofMoveSingleTool.ts
  src/ProofTools/ProofMoveUtils.ts
  src/ProofTools/ProofResizeTool.ts
  src/ProofTools/pasteInProof.ts
  src/ToggleModes.ts
  src/index.css
  src/index.html
  src/index.ts
  src/treeContext.ts
Labels: enhancement, required

#283 Better delete mode highlights
  src/DrawModes/CopyFromDraw.ts
  src/DrawModes/DeleteMultiTool.ts
  src/DrawModes/DeleteSingleTool.ts
  src/ProofTools/DeiterationTool.ts
  src/ProofTools/DoubleCutDeletionTool.ts
  src/ProofTools/ErasureTool.ts
  src/SharedToolUtils/DrawUtils.ts
  src/SharedToolUtils/EditModeUtils.ts
Labels: bug, required

#276 Documentation and wording stuff!
  src/AEG/AEGTree.ts
  src/AEG/AEGUtils.ts
  src/AEG/AtomNode.ts
  src/AEG/CutNode.ts
  src/AEG/Ellipse.ts
  src/AEG/Point.ts
  src/AEG/ProofNode.ts
  src/AEG/Rectangle.ts
  src/about.html
  typedoc.json
Labels: documentation, User Interface

#302 SharedToolUtils Docs!
  src/AEG/AEGUtils.ts
  src/SharedToolUtils/DragTool.ts
  src/SharedToolUtils/DrawUtils.ts
  src/SharedToolUtils/EditModeUtils.ts
  src/index.ts
Labels: documentation

#311 Custom Cursors!
  src/DrawModes/AtomTool.ts
  src/DrawModes/CopyFromDraw.ts
  src/DrawModes/CopyMultiTool.ts
  src/DrawModes/CopySingleTool.ts
  src/DrawModes/CutTool.ts
  src/DrawModes/MoveMultiTool.ts
  src/DrawModes/MoveSingleTool.ts
  src/DrawModes/ResizeTool.ts
  src/ProofTools/DoubleCutInsertionTool.ts
  src/ProofTools/InsertionTools.ts
  src/ProofTools/IterationTool.ts
  src/ProofTools/PasteInProof.ts
  src/ProofTools/ProofMoveMultiTool.ts
  src/ProofTools/ProofMoveSingleTool.ts
  src/ProofTools/ProofResizeTool.ts
  src/SharedToolUtils/DragTool.ts
  src/SharedToolUtils/DrawUtils.ts
  src/index.html
  src/index.ts
Labels: enhancement, optional, User Interface

#310 DrawTools Documentation
  .vscode/settings.json
  src/DrawTools/AtomTool.ts
  src/DrawTools/CopyFromDraw.ts
  src/DrawTools/CopyMultiTool.ts
  src/DrawTools/CopySingleTool.ts
  src/DrawTools/CutTool.ts
  src/DrawTools/DeleteMultiTool.ts
  src/DrawTools/DeleteSingleTool.ts
  src/DrawTools/MoveMultiTool.ts
  src/DrawTools/MoveSingleTool.ts
  src/DrawTools/ResizeTool.ts
  src/index.ts
Labels: documentation

#321 Get Playwright off the Master Branch!
  .github/workflows/playwright.yml
Labels: bug

#182 Gource!
  .github/workflows/gource.yml
  .mailmap
  .vscode/settings.json
Labels: enhancement

#328 /ProofTools/ Docs!
  .github/CONTRIBUTING.md
  .mailmap
  .vscode/settings.json
  src/AEG/AEGTree.ts
  src/AEG/CutNode.ts
  src/AEG/Point.ts
  src/AEG/ProofNode.ts
  src/DrawTools/AtomTool.ts
  src/DrawTools/CopyFromDraw.ts
  src/DrawTools/CopyMultiTool.ts
  src/DrawTools/CopySingleTool.ts
  src/DrawTools/CutTool.ts
  src/DrawTools/DeleteMultiTool.ts
  src/DrawTools/DeleteSingleTool.ts
  src/DrawTools/DrawResizeTool.ts
  src/DrawTools/MoveMultiTool.ts
  src/DrawTools/MoveSingleTool.ts
  src/ProofHistory.ts
  src/ProofTools/ClearProofTool.ts
  src/ProofTools/DeiterationTool.ts
  src/ProofTools/DoubleCutDeletionTool.ts
  src/ProofTools/DoubleCutInsertionTool.ts
  src/ProofTools/ErasureTool.ts
  src/ProofTools/InsertionTool.ts
  src/ProofTools/IterationTool.ts
  src/ProofTools/PasteInProof.ts
  src/ProofTools/ProofMoveMultiTool.ts
  src/ProofTools/ProofMoveSingleTool.ts
  src/ProofTools/ProofResizeTool.ts
  src/ProofTools/ProofToolUtils.ts
  src/ProofTools/ProofToolsUtils.ts
  src/SharedToolUtils/DragTool.ts
  src/SharedToolUtils/DrawUtils.ts
  src/SharedToolUtils/EditModeUtils.ts
  src/Themes.ts
  src/ToggleModes.ts
  src/TreeContext.ts
  src/index.ts
  typedoc.json
Labels: documentation

#333 /src/ Docs! No more undergrads!
  src/AEG-IO.ts
  src/ProofHistory.ts
  src/Themes.ts
  src/ToggleModes.ts
  src/TreeContext.ts
  src/index.html
  src/index.ts
Labels: documentation

#335 Resize: Reworked and Remastered!
  src/SharedToolUtils/EditModeUtils.ts
Labels: bug
