Repository RAIRLab/Peirce-My-Heart, pull requests merged in 2023-10, with the labels that each got.

#85 Isuse #50 prevent non letters from being selected.
  src/AtomCreation.ts
Labels: bug

#99 rectangle overlap when no corners within bug fix
  src/AEG/Ellipse.ts
  src/AEG/Rectangle.ts
Labels: bug

#103 Ellipse collision detection bug
  .vscode/settings.json
  src/AEG/Ellipse.ts
  src/AEG/Rectangle.ts
Labels: bug

#114 110 more points on ellipses for collison check
  src/AEG/AEGTree.ts
  src/AEG/AEGUtils.ts
  src/AEG/AtomNode.ts
  src/AEG/CutNode.ts
  src/AEG/Ellipse.ts
  src/AEG/Rectangle.ts
  src/AtomMode.ts
  src/CutMode.ts
  src/index.ts
Labels: bug, enhancement

#115 no executions on my watch
  src/AEG/AEGTree.ts
Labels: bug

#84 29: Tests with Vitest
  .eslintignore
  .github/workflows/runTests.yml
  .npmignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  src/AEG/AEGTree.ts
  src/AEG/AtomNode.ts
  src/AEG/CutNode.ts
  src/AEG/Ellipse.ts
  src/AEG/Point.ts
  src/AEG/Rectangle.ts
  src/EllipseCreation.ts
  tests/Ellipse.test.ts
  tests/Point.test.ts
  tests/Rectangle.test.ts
  tsconfig.json
  vite.config.js
Labels: enhancement, required

#122 Temporary Master Fix
  src/AEG/AtomNode.ts
Labels: bug

#126 AtomNode tests
  .vscode/settings.json
  src/AEG/AEGTree.ts
  src/AEG/AEGUtils.ts
  src/AEG/AtomNode.ts
  src/AEG/Ellipse.ts
  src/AEG/Point.ts
  src/AEG/Rectangle.ts
  src/AtomMode.ts
  src/CutMode.ts
  tests/AtomNode.test.ts
  tests/Ellipse.test.ts
  tests/Point.test.ts
  tests/Rectangle.test.ts
Labels: bug, required

#129 Support for progressive web app
  .gitignore
  .vscode/settings.json
  README.md
  public/PeirceMyHeart.webmanifest
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  src/index.html
Labels: enhancement

#150 All requested workflow changes!
  .github/workflows/buildAndDeploy.yml
  .github/workflows/buildElectronArtifcact.yml
  .github/workflows/lint.yml
  .github/workflows/runTests.yml
  .github/workflows/validateBuild.yml
  .github/workflows/validateBuildElectron.yml
  .github/workflows/validateDocs.yml
  .github/workflows/validateHTML.yml
Labels: enhancement

#155 Bounding Box Bug Fix
  src/AtomMode.ts
Labels: bug

#160 Potential remove fix and comprehensive CutNode tests!
  src/AEG/CutNode.ts
  tests/CutNode.test.ts
  tests/Ellipse.test.ts
Labels: bug, required

#164 Save shortcut!
  src/index.ts
Labels: enhancement, required

#159 Comprehensive AEGTree tests!
  src/AEG/AEGTree.ts
  tests/AEGTree.test.ts
Labels: enhancement, required

#173 42 button click indicator and squished UI
  src/index.css
  src/index.html
  src/index.ts
  src/style.css
Labels: bug, required

#175 Changeable themes, lint line ending fix
  .eslintrc.json
  .vscode/settings.json
  src/AtomMode.ts
  src/CutMode.ts
  src/Themes.ts
  src/index.css
  src/index.html
  src/index.ts
  src/themes.css
Labels: enhancement, optional, User Interface

#183 Delete!
  src/DeleteMultiMode.ts
  src/DeleteSingleMode.ts
  src/index.ts
Labels: required

#201 Offsets now update properly in both Delete modes, delete fixed
  src/DeleteMultiMode.ts
  src/DeleteSingleMode.ts
Labels: bug, required
