Repository RAIRLab/Peirce-My-Heart, pull requests merged in 2024-01, with the labels that each got.

#336 Larger vitest suite! Also organization!
  .github/workflows/buildAndDeploy.yml
  .github/workflows/buildElectronArtifcact.yml
  .github/workflows/gource.yml
  .github/workflows/lint.yml
  .github/workflows/playwright.yml
  .github/workflows/runTests.yml
  .github/workflows/validateBuild.yml
  .github/workflows/validateBuildElectron.yml
  .github/workflows/validateDocs.yml
  .github/workflows/validateHTML.yml
  package.json
  src/AEG-IO.ts
  src/AEG/AEGTree.ts
  src/AEG/AtomNode.ts
  src/AEG/CutNode.ts
  src/AEG/Ellipse.ts
  src/AEG/Point.ts
  src/AEG/Rectangle.ts
  src/CSS/index.css
  src/CSS/style.css
  src/CSS/themes.css
  src/DrawTools/DeleteMultiTool.ts
  src/DrawTools/DeleteSingleTool.ts
  src/Proof/ProofHistory.ts
  src/Proof/ProofNode.ts
  src/ProofTools/ClearProofTool.ts
  src/ProofTools/DeiterationTool.ts
  src/ProofTools/DoubleCutDeletionTool.ts
  src/ProofTools/DoubleCutInsertionTool.ts
  src/ProofTools/ErasureTool.ts
  src/ProofTools/InsertionTool.ts
  src/ProofTools/IterationTool.ts
  src/ProofTools/PasteInProof.ts
  src/ProofTools/ProofMoveMultiTool.ts
  src/ProofTools/ProofMoveSingleTool.ts
  src/ProofTools/ProofResizeTool.ts
  src/ToggleModes.ts
  src/TreeContext.ts
  src/index.html
  src/index.ts
  tests/AEGTree/AEGTree.test.ts
  tests/AEGTree/AEGUtils.test.ts
  tests/AEGTree/AtomNode.test.ts
  tests/AEGTree/CutNode.test.ts
  tests/AEGTree/Ellipse.test.ts
  tests/AEGTree/Point.test.ts
  tests/AEGTree/Rectangle.test.ts
  typedoc.json
Labels: Non API-Breaking Feature

#342 341 fix external dependencies to use npm
  package-lock.json
  package.json
  src/AEG-IO.ts
  src/AEG/AEGTree.ts
  src/AEG/AEGUtils.ts
  src/AEG/AtomNode.ts
  src/AEG/CutNode.ts
  src/AEG/Ellipse.ts
  src/AEG/Point.ts
  src/AEG/Rectangle.ts
  src/CSS/index.css
  src/DrawTools/AtomTool.ts
  src/DrawTools/CopyFromDraw.ts
  src/DrawTools/CopyMultiTool.ts
  src/DrawTools/CopySingleTool.ts
  src/DrawTools/CutTool.ts
  src/DrawTools/DeleteMultiTool.ts
  src/DrawTools/DeleteSingleTool.ts
  src/DrawTools/DrawResizeTool.ts
  src/DrawTools/MoveMultiTool.ts
  src/DrawTools/MoveSingleTool.ts
  src/Proof/ProofHistory.ts
  src/Proof/ProofNode.ts
  src/ProofTools/ClearProofTool.ts
  src/ProofTools/DeiterationTool.ts
  src/ProofTools/DoubleCutDeletionTool.ts
  src/ProofTools/DoubleCutInsertionTool.ts
  src/ProofTools/ErasureTool.ts
  src/ProofTools/InsertionTool.ts
  src/ProofTools/IterationTool.ts
  src/ProofTools/PasteInProof.ts
  src/ProofTools/ProofMoveMultiTool.ts
  src/ProofTools/ProofMoveSingleTool.ts
  src/ProofTools/ProofResizeTool.ts
  src/ProofTools/ProofToolUtils.ts
  src/SharedToolUtils/DragTool.ts
  src/SharedToolUtils/DrawUtils.ts
  src/SharedToolUtils/EditModeUtils.ts
  src/Themes.ts
  src/ToggleModes.ts
  src/TreeContext.ts
  src/index.html
  tests/AEGTree/AEGTree.test.ts
  tests/AEGTree/AEGUtils.test.ts
  tests/AEGTree/AtomNode.test.ts
  tests/AEGTree/CutNode.test.ts
  tests/AEGTree/Ellipse.test.ts
  tests/AEGTree/Point.test.ts
  tests/AEGTree/Rectangle.test.ts
Labels: Bug, dependencies, No API-Break

#346 Left mosue only!
  src/DrawTools/CutTool.ts
  src/index.ts
Labels: Bug
